package demo

import demo.autogenerated._

object Main extends App {
  println("Hello World!") // Tradition Matters!!

  val nameToId: Map[String, Int] = for {
    inspection <- AllScapegoatInspections
  } yield (inspection.name -> inspection.id)

  println(nameToId.mkString("\n"))
}
