package demo

import demo.autogenerated._

object Main extends App {
  println("Hello World!") // Tradition Matters!!

  val nameToId = for {
    inspection <- AllScapegoatInspections
  } yield (inspection.name -> inspection.id)

  println(nameToId.toMap.mkString("\n"))
}
